# Generated by Django 5.0 on 2025-03-11 20:06

from django.db import migrations


def populate_currencies(apps, schema_editor):
    Currency = apps.get_model("rates", "Currency")

    currencies = [
        {"name": "Euro", "code": "EUR", "symbol": "€"},
        {"name": "Swiss Franc", "code": "CHF", "symbol": "CHF"},
        {"name": "US Dollar", "code": "USD", "symbol": "$"},
        {"name": "Pound Sterling", "code": "GBP", "symbol": "£"},
    ]

    for currency_data in currencies:
        Currency.objects.update_or_create(
            code=currency_data["code"], defaults=currency_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_currencies),
    ]
