# Generated by Django 5.0 on 2025-03-23 11:33

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0005_populate_providers"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchProcess",
            fields=[
                (
                    "process_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("FAILED", "Failed"),
                            ("DONE", "Done"),
                        ],
                        default="PROCESSING",
                        max_length=10,
                    ),
                ),
                ("processes", models.IntegerField(default=0)),
                (
                    "starting_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ending_time", models.DateTimeField(blank=True, null=True)),
                ("processes_counter", models.IntegerField(default=0)),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_processes",
                        to="rates.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["starting_time"],
            },
        ),
    ]
